language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

matrix:
  allow_failures:
    # mysterious RPython KeyError's may happen
    - python: pypy

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  # replace with the correct version of .coveragerc, when run under Python 3
  - [ "x${TRAVIS_PYTHON_VERSION%.?}" == "x3" ] && ( rm .coveragerc && ln -s .coveragerc.py3 .coveragerc ) ; true

script: nosetests --with-coverage

after_success:
  - coveralls

notifications:
  email: false


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
