language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

matrix:
  allow_failures:
    # mysterious RPython KeyError's may happen
    - python: pypy

install:
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt
  - pip install coveralls

before_script:
  # replace with the correct version of .coveragerc, when run under Python 3
  - "if [[ \"x${TRAVIS_PYTHON_VERSION%.?}\" == \"x3\" ]]; then echo Switching .coveragerc to Python 3 version. ; rm .coveragerc && ln -s .coveragerc.py3 .coveragerc ) ; fi"
  - ls -l .coveragerc

script: nosetests --with-coverage

after_success:
  - coveralls

notifications:
  email: false


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
